#pragma once
#include <cstdint>
#include <string_view>

constexpr const char* HangedmanStages[][8] = {
    {"  _________",
     "  |/      |",
     "  |",
     "  |",
     "  |",
     "  |",
     "  |",
     "__|___"},
    {"  _________",
     "  |/      |",
     "  |      (_)",
     "  |",
     "  |",
     "  |",
     "  |",
     "__|___"},
    {"  _________",
     "  |/      |",
     "  |      (_)",
     "  |       |",
     "  |",
     "  |",
     "  |",
     "__|___"},
    {"  _________",
     "  |/      |",
     "  |      (_)",
     "  |       |",
     "  |       |",
     "  |",
     "  |",
     "__|___"},
     {"  _________",
      "  |/      |",
      "  |      (_)",
      "  |       |",
      "  |       |",
      "  |        \\",
      "  |",
      "__|___"},
     {"  _________",
      "  |/      |",
      "  |      (_)",
      "  |       |",
      "  |       |",
      "  |      / \\",
      "  |",
      "__|___"},
     {"  _________",
      "  |/      |",
      "  |      (_)",
      "  |      \\|",
      "  |       |",
      "  |      / \\",
      "  |",
      "__|___"},
     {"  _________",
      "  |/      |",
      "  |      (_)",
      "  |      \\|/",
      "  |       |",
      "  |      / \\",
      "  |",
      "__|___"}
};
using std::size_t;
constexpr size_t MinTries = 1;
constexpr size_t MaxTries = sizeof(HangedmanStages)/sizeof(*HangedmanStages);
constexpr size_t HangedmanWidth =
    std::string_view(HangedmanStages[0][0]).size()+1;
constexpr size_t HangedmanHeight = 8;
